/* Generated By:JavaCC: Do not edit this line. CompilateurConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilateurConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FLOAT = 1;
  /** RegularExpression Id. */
  int NOMBRE = 2;
  /** RegularExpression Id. */
  int BOOLEAN = 3;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int NAN = 5;
  /** RegularExpression Id. */
  int IMPORT = 6;
  /** RegularExpression Id. */
  int IDENT = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<FLOAT>",
    "<NOMBRE>",
    "<BOOLEAN>",
    "<EOL>",
    "\"NaN\"",
    "\"import\"",
    "<IDENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 11>",
    "<token of kind 12>",
    "\"{\"",
    "\"}\"",
    "\"==\"",
    "\">=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\"!=\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
  };

}
