/* Generated By:JavaCC: Do not edit this line. CompilateurConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilateurConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOMBRE = 3;
  /** RegularExpression Id. */
  int EOL = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<NOMBRE>",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
