/* Compilateur.java */
/* Generated By:JavaCC: Do not edit this line. Compilateur.java */
import AST.*;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.io.InputStream;

public class Compilateur implements CompilateurConstants {
    public static void main(String args[]) {
        try {
            //System.out.print("Tapez une Expression : ");
            FileInputStream fis = new FileInputStream("test.js");
            Compilateur parseur = new Compilateur(fis);
            Programme programme = parseur.mainNT(); // Changer pour Programme
            System.out.println("Assembly code  : \n" + programme.toAssembly()+"Halt"); // Modifier pour générer l'assembleur
            System.out.println("C'est bien une expression arithm\u00e9tique !!");
        }catch (FileNotFoundException e) {
            System.out.println("Le fichier sp\u00e9cifi\u00e9 n'a pas \u00e9t\u00e9 trouv\u00e9.");
        }catch (TokenMgrError e) {
            System.out.println("Ceci n'est pas une expression arithm\u00e9tique :"+e.toString());
        }catch (ParseException e){
            System.out.println("Ceci n'est pas une expression arithm\u00e9tique :"+e);
    }   }

  static final public Programme mainNT() throws ParseException {Programme prg;
    prg = programme();
    jj_consume_token(0);
{if ("" != null) return prg;}
    throw new Error("Missing return statement in function");
}

  static final public Programme programme() throws ParseException {List<Commande> programme = new ArrayList<>();
    Commande commande;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FLOAT:
      case NOMBRE:
      case BOOLEAN:
      case IMPORT:
      case IDENT:
      case 13:
      case 23:
      case 27:
      case 29:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      commande = commande();
programme.add(commande);
    }
{if ("" != null) return new Programme(programme);}
    throw new Error("Missing return statement in function");
}

  static final public Commande commande() throws ParseException {Commande expr;
    Programme prg;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case FLOAT:
    case NOMBRE:
    case BOOLEAN:
    case IDENT:
    case 23:
    case 27:
    case 29:{
      expr = expression();
      jj_consume_token(EOL);
{if ("" != null) return expr;}
      break;
      }
    case IMPORT:{
      jj_consume_token(IMPORT);
      expr = facteur();
      jj_consume_token(EOL);
{if ("" != null) return new Import(expr);}
      break;
      }
    case 13:{
      jj_consume_token(13);
      prg = programme();
      jj_consume_token(14);
{if ("" != null) return new Bloc(prg);}
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public ExpressionA expression() throws ParseException {ExpressionA gauche, droite;
    gauche = comp();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 15:
      case 16:
      case 17:
      case 18:
      case 19:
      case 20:
      case 21:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 15:{
        jj_consume_token(15);
        droite = comp();
gauche = new Egal(gauche, droite);
        break;
        }
      case 16:{
        jj_consume_token(16);
        droite = comp();
gauche = new GrEgNb(gauche, droite);
        break;
        }
      case 17:{
        jj_consume_token(17);
        droite = comp();
gauche = new GrStNb(gauche, droite);
        break;
        }
      case 18:{
        jj_consume_token(18);
        droite = comp();
gauche = new LoStNb(gauche, droite);
        break;
        }
      case 19:{
        jj_consume_token(19);
        droite = comp();
gauche = new LoEqNb(gauche, droite);
        break;
        }
      case 20:{
        jj_consume_token(20);
        droite = comp();
gauche = new NotEql(gauche, droite);
        break;
        }
      case 21:{
        jj_consume_token(21);
        droite = comp();
gauche = new Et(gauche, droite);
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return gauche;}
    throw new Error("Missing return statement in function");
}

  static final public ExpressionA comp() throws ParseException {ExpressionA gauche, droite;
    gauche = terme();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 22:
      case 23:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 22:{
        jj_consume_token(22);
        droite = terme();
gauche = new Plus(gauche, droite);
        break;
        }
      case 23:{
        jj_consume_token(23);
        droite = terme();
gauche = new Moins(gauche, droite);
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return gauche;}
    throw new Error("Missing return statement in function");
}

  static final public ExpressionA terme() throws ParseException {ExpressionA gauche, droite;
    gauche = facteur();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 24:
      case 25:
      case 26:{
        ;
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 24:{
        jj_consume_token(24);
        droite = facteur();
gauche = new Mult(gauche, droite);
        break;
        }
      case 25:{
        jj_consume_token(25);
        droite = facteur();
gauche = new Div(gauche, droite);
        break;
        }
      case 26:{
        jj_consume_token(26);
        droite = facteur();
gauche = new Modulo(gauche, droite);
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return gauche;}
    throw new Error("Missing return statement in function");
}

  static final public ExpressionA facteur() throws ParseException {ExpressionA expr;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 27:{
      jj_consume_token(27);
      expr = expression();
      jj_consume_token(28);
{if ("" != null) return expr;}
      break;
      }
    case 23:{
      jj_consume_token(23);
      expr = facteur();
{if ("" != null) return new Neg(expr);}
      break;
      }
    case 29:{
      jj_consume_token(29);
      expr = facteur();
{if ("" != null) return new Not(expr);}
      break;
      }
    case NOMBRE:{
      jj_consume_token(NOMBRE);
{if ("" != null) return new Num(Integer.parseInt(token.image));}
      break;
      }
    case FLOAT:{
      jj_consume_token(FLOAT);
{if ("" != null) return new FloatT(Float.parseFloat(token.image));}
      break;
      }
    case BOOLEAN:{
      jj_consume_token(BOOLEAN);
{if ("" != null) return new Bool(Boolean.parseBoolean(token.image));}
      break;
      }
    case IDENT:{
      jj_consume_token(IDENT);
{if ("" != null) return new Ident(token.image);}
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CompilateurTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[9];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x288020ce,0x288020ce,0x3f8000,0x3f8000,0xc00000,0xc00000,0x7000000,0x7000000,0x2880008e,};
	}

  /** Constructor with InputStream. */
  public Compilateur(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compilateur(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new CompilateurTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Compilateur(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new CompilateurTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new CompilateurTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Compilateur(CompilateurTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompilateurTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[30];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 9; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 30; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
